### PR TITLE
0.4.0 - Update Flow Router support

### PR DESCRIPTION
**Pull request by deanrad**
- [x] Get a +1 from another contributor/user

Then merge, then: 
- [x] Release to atmosphere
- [ ] Announce on crater

### CODE REVIEW

**Comment by acemtp** [comment]
Perhaps we should use something like that to catch all path changes:

```
Tracker.autorun(() => {
  FlowRouter.watchPathChange();
  const currentContext = FlowRouter.current();
  if (currentContext && currentContext.path) analytics.page(currentContext.path);
});
```

**Comment by pauldowman** [comment]
:+1:

**Comment by deanrad** [comment]
@acemtp - are you suggesting using that instead of the hooks ? Is there a case the autorun catches that hooks don't  ?

**Comment by deanrad** [comment]
Should start having some tests in here no ?

**Comment by acemtp** [comment]
@deanius I don't know if the solution is better or not. Just that in the flow router doc, it seems to be the easiest way to track page change.

https://github.com/kadirahq/flow-router#flowrouterwatchpathchange

**Pull request merged**
