### PR TITLE
Flow Router 2.0.0 support

### PR DESCRIPTION
**Pull request by tomwasd**
The new flow router has changed the package name to kadira:flow-router and changed from FlowLayout to BlazeLayout.

I think this PR makes everything work with the new version :)

### CODE REVIEW

**Comment by lukasvan3l** [comment]
good one, though I would prefer to maintain support for Flow Router 1.0, which can easily be achieved like this: https://github.com/lukasvan3l/analytics/commit/55616d1da2852b1758b69873dc24fb6b16c31e93

**Comment by pauldowman** [comment]
Thanks @tomwasd we'll try this out and merge ASAP. @lukasvan3l thanks also, I assume we would need FlowLayout/BlazeLayout conditionals too.

**Comment by lukasvan3l** [comment]
I don't know the specifics of that yet, but I can imagine next to FlowLayout and BlazeLayout there's also ReactLayout.

**Comment by deanrad** [comment]
I've moved it and addressed the issue in PR #53.. Can you check that out ? 

Also, @pauldowman I've updated the sample application to use the correct layouts, the core analytics package doesn't use them and didn't need updating

**Pull request closed without merging**
